#[allow(dead_code)]
pub enum CommandId {
    AssociationRequest = 0x01,
    AssociationResponse = 0x02,
    DisassociationNotification = 0x03,
    DataRequest = 0x04,
    PanIdConflictNotification = 0x05,
    OrphanNotification = 0x06,
    BeaconRequest = 0x07,
    CoordinatorRealignment = 0x08,
    GtsRequest = 0x09,
    TrleManagementRequest = 0x0a,
    TrleManagementResponse = 0x0b,
    DsmeAssociationRequest = 0x13,
    DsmeAssociationResponse = 0x14,
    DsmeGtsRequest = 0x15,
    DsmeGtsResponse = 0x16,
    DsmeGtsNotify = 0x17,
    DsmeInformationRequest = 0x18,
    DsmeInformationResponse = 0x19,
    DsmeBeaconAllocationNotification = 0x1a,
    DsmeBeaconCollisionNotification = 0x1b,
    DsmeLinkReport = 0x1c,
    RitDataRequest = 0x20,
    DbsRequest = 0x21,
    DbsResponse = 0x22,
    RitDataResponse = 0x23,
    VendorSpecific = 0x24,
    SrmRequest = 0x25,
    SrmResponse = 0x26,
    SrmReport = 0x27,
    SrmInformation = 0x28,
}
