[default.probe]
speed = 10000 # Configure lower speeds in case of connection issues.

[default.general]
chip = "nRF52840_xxAA"

[default.flashing]
enabled = false

[flash.flashing]
enabled = true
verify = false

[rtt.reset]
enabled = true

[rtt.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "NoBlockSkip", format = "Defmt", show_location = false },
]
down_channels = [{ channel = 0, mode = "NoBlockSkip" }]
tabs = [{ up_channel = 0, down_channel = 0, name = "Terminal" }]
